# Generated by Django 4.2.19 on 2025-03-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
